import { Theme } from '../../interfaces';

export const defaultTheme: Theme = {
  name: 'defaultTheme',
  properties: {
    '--hue-color': '210',
    '--first-color-second': 'hsl(var(--hue-color), 69%, 61%)',
    '--first-color-second-hover': 'hsl(var(--hue-color), 69%, 51%)',
    '--primary-color': 'hsl(var(--hue-color), 69%, 61%)',
    '--primary-color-hover': 'hsl(var(--hue-color), 69%, 51%)',
    '--title-color': 'hsl(var(--hue-color), 8%, 15%)',
    '--text-color': 'hsl(var(--hue-color), 8%, 45%)',
    '--input-color': 'hsl(var(--hue-color), 70%, 96%)',
    '--body-color': 'hsl(var(--hue-color), 60%, 99%)',
    '--body-color-hover': 'hsl(var(--hue-color), 60%, 90%)',
    '--scroll-bar-color': 'hsl(var(--hue-color), 12%, 90%)',
    '--scroll-thumb-color': 'hsl(var(--hue-color), 12%, 80%)',
    '--container-color': 'hsl(var(--hue-color), 0%, 100%)',
    '--color-menu-bg': 'hsl(var(--hue-color), 28%, 12%)',
    '--color-text-logo': 'hsl(var(--hue-color), 28%, 12%)',
    '--card-bg-color': 'hsl(var(--hue-color), 0%, 100%)',
    '--table-bg-color': 'hsl(var(--hue-color), 60%, 98%)',
    '--success-color': 'hsl(var(--hue-color), 65%, 56%)',
    '--warning-color': 'hsl(45, 100%, 50%)',
    '--warning-color-hover': 'hsl(45, 100%, 40%)',
    '--warning-text-color': '#ffffff',
    '--error-text-color': '#ffffff',
    '--disabled-text-color': '#666666',
    '--error-color': 'hsl(0, 100%, 50%)',
    '--error-color-hover': 'hsl(0, 100%, 40%)',
    '--disabled-bg-color': '#cccccc',
    '--info-color': 'hsl(var(--hue-color), 75%, 60%)',
    '--info-color-hover': 'hsl(var(--hue-color), 75%, 50%)',
    '--second-color': 'hsl(var(--hue-color), 75%, 60%)',
    '--second-color-hover': 'hsl(var(--hue-color), 75%, 50%)',
    '--hover-bg-color': 'hsl(var(--hue-color), 12%, 90%)',
    '--active-bg-color': 'hsl(var(--hue-color), 12%, 80%)',
    '--border-color': 'hsl(var(--hue-color), 15%, 80%)',
    '--font-size-small': '12px',
    '--font-size-medium': '14px',
    '--font-size-large': '16px',
    '--font-family': "'Roboto', sans-serif",
    '--box-shadow': '0 4px 8px rgba(0, 0, 0, 0.1)',
    '--transition-duration': '0.3s',
  },
};

export const light: Theme = {
  name: 'light',
  properties: {
    '--hue-color': '225',
    '--first-color-second': 'hsl(var(--hue-color), 69%, 45%)',
    '--first-color-second-hover': 'hsl(var(--hue-color), 69%, 41%)',
    '--primary-color': 'hsl(var(--hue-color), 75%, 50%)',
    '--primary-color-hover': 'hsl(var(--hue-color), 75%, 45%)',
    '--body-bg-color': 'hsl(var(--hue-color), 15%, 86%)',
    '--body-color': 'hsl(var(--hue-color), 60%, 99%)',
    '--template-color': 'hsl(var(--hue-color), 60%, 99%)',
    '--text-color': 'hsl(var(--hue-color), 8%, 45%)',
    '--body-color-hover': 'hsl(var(--hue-color), 60%, 90%)',
    '--title-color': 'hsl(var(--hue-color), 100%, 25%)',
    '--button-bg-color': 'hsl(var(--hue-color), 53%, 79%)',
    '--button-bg-color-hover': 'hsl(var(--hue-color), 53%, 69%)',
    '--button-border-color': 'hsl(var(--hue-color), 0%, 100%)',
    '--button-text-color': 'hsl(var(--hue-color), 0%, 100%)',
    '--magic-box-bg-color': 'hsl(var(--hue-color), 0%, 100%)',
    '--magic-box-text-color': 'hsl(var(--hue-color), 63%, 29%)',
    '--card-bg-color': 'hsl(var(--hue-color), 0%, 100%)',
    '--table-bg-color': 'hsl(var(--hue-color), 60%, 98%)',
    '--success-color': 'hsl(var(--hue-color), 65%, 56%)',
    '--success-color-hover': 'hsl(var(--hue-color), 65%, 46%)',
    '--warning-color': 'hsl(45, 100%, 50%)',
    '--warning-color-hover': 'hsl(45, 100%, 40%)',
    '--warning-text-color': '#ffffff',
    '--disabled-bg-color': '#cccccc',
    '--disabled-bg-color-hover': '#bbbbbb',
    '--error-text-color': '#ffffff',
    '--disabled-text-color': '#666666',
    '--error-color': 'hsl(0, 100%, 50%)',
    '--error-color-hover': 'hsl(0, 100%, 40%)',
    '--info-color': 'hsl(var(--hue-color), 75%, 60%)',
    '--info-color-hover': 'hsl(var(--hue-color), 75%, 50%)',
    '--second-color': 'hsl(var(--hue-color), 75%,40%)',
    '--second-color-hover': 'hsl(var(--hue-color), 75%, 35%)',
    '--hover-bg-color': 'hsl(var(--hue-color), 12%, 90%)',
    '--active-bg-color': 'hsl(var(--hue-color), 12%, 80%)',
    '--border-color': 'hsl(var(--hue-color), 15%, 80%)',
    '--font-size-small': '12px',
    '--font-size-medium': '14px',
    '--font-size-large': '16px',
    '--font-family': "'Roboto', sans-serif",
    '--box-shadow': '0 4px 8px rgba(0, 0, 0, 0.1)',
    '--transition-duration': '0.3s',
  },
};

export const dark: Theme = {
  name: 'dark',
  properties: {
    '--hue-color': '210',
    '--first-color-second': 'hsl(var(--hue-color), 30%, 8%)',
    '--first-color-second-hover': 'hsl(var(--hue-color), 30%, 18%)',
    '--primary-color': 'hsl(var(--hue-color), 75%, 50%)',
    '--primary-color-hover': 'hsl(var(--hue-color), 75%, 47%)',
    '--title-color': 'hsl(var(--hue-color), 8%, 95%)',
    '--text-color': 'hsl(var(--hue-color), 8%, 75%)',
    '--input-color': 'hsl(var(--hue-color), 29%, 16%)',
    '--box-shadow-input': 'hsla(var(--hue-color), 75%, 50%, 0.3)',
    '--body-color': '#0e0e11',
    '--template-color': 'hsla(240, 6%, 10%, 0.96)',
    '--body-color-hover': 'hsl(var(--hue-color), 28%, 22%)',
    '--container-color': 'hsl(var(--hue-color), 29%, 16%)',
    '--scroll-bar-color': 'hsl(var(--hue-color), 12%, 48%)',
    '--scroll-thumb-color': 'hsl(var(--hue-color), 12%, 36%)',
    '--color-menu-bg': 'hsl(var(--hue-color), 28%, 12%)',
    '--color-text-logo': 'hsl(var(--hue-color), 0%, 100%)',
    '--card-bg-color': 'hsl(var(--hue-color), 29%, 16%)',
    '--table-bg-color': 'hsl(var(--hue-color), 28%, 12%)',
    '--success-color': 'hsl(var(--hue-color), 65%, 56%)',
    '--success-color-hover': 'hsl(var(--hue-color), 65%, 46%)',
    '--warning-color': 'hsl(45, 100%, 50%)',
    '--warning-color-hover': 'hsl(45, 100%, 40%)',
    '--warning-text-color': '#ffffff',
    '--disabled-text-color': '#666666',
    '--disabled-bg-color': '#cccccc',
    '--disabled-bg-color-hover': '#bbbbbb',
    '--error-text-color': '#ffffff',
    '--error-color': 'hsl(0, 100%, 50%)',
    '--error-color-hover': 'hsl(0, 100%, 40%)',
    '--info-color': 'hsl(var(--hue-color), 75%, 60%)',
    '--info-color-hover': 'hsl(var(--hue-color), 75%, 50%)',
    '--second-color': 'hsl(var(--hue-color), 75%, 40%)',
    '--second-color-hover': 'hsl(var(--hue-color), 75%, 38%)',
    '--hover-bg-color': 'hsl(var(--hue-color), 12%, 48%)',
    '--active-bg-color': 'hsl(var(--hue-color), 12%, 36%)',
    '--border-color': 'hsl(var(--hue-color), 12%, 20%)',
    '--font-size-small': '12px',
    '--font-size-medium': '14px',
    '--font-size-large': '16px',
    '--font-family': "'Roboto', sans-serif",
    '--box-shadow': '0 4px 8px rgba(0, 0, 0, 0.1)',
    '--transition-duration': '0.3s',
  },
};

export const purple: Theme = {
  name: 'purple',
  properties: {
    '--hue-color': '270',
    '--primary-color': 'hsl(var(--hue-color), 100%, 50%)',
    '--primary-color-hover': 'hsl(var(--hue-color), 100%, 55%)',
    '--second-color': 'hsl(var(--hue-color), 100%, 40%)',
    '--second-color-hover': 'hsl(var(--hue-color), 100%, 35%)',
  },
};

export const green: Theme = {
  name: 'green',
  properties: {
    '--hue-color': '120',
    '--primary-color': 'hsl(var(--hue-color), 60%, 40%)',
    '--primary-color-hover': 'hsl(var(--hue-color), 60%, 35%)',
    '--second-color': 'hsl(var(--hue-color), 60%, 30%)',
    '--second-color-hover': 'hsl(var(--hue-color), 60%, 25%)',
    // '--primary-color': 'hsl(var(--hue-color), 82%, 20%)',
    // '--primary-color-hover': 'hsl(var(--hue-color), 82%, 14%)',
  },
};

export const pink: Theme = {
  name: 'pink',
  properties: {
    '--hue-color': '340',
    '--primary-color': 'hsl(var(--hue-color), 69%, 61%)',
    '--primary-color-hover': 'hsl(var(--hue-color), 69%, 59%)',
    '--second-color': 'hsl(var(--hue-color), 69%, 51%)',
    '--second-color-hover': 'hsl(var(--hue-color), 69%, 46%)',
  },
};

export const macLight: Theme = {
  name: 'macLight',
  properties: {
    '--text-primary-color': '#000000',
    '--select_background': 'rgba(0, 0, 0, 0.05)',
    '--icon-backgound': '#ffffff',
    '--background-color': '#f6f6f6',
    '--breadcrumbs-disabled': 'rgba(0, 0, 0, 0.4)',
    '--breadcrumbs-line': 'rgba(0, 0, 0, 0.4)',
    '--box-shadow-select': '0px 1px 0px 0px rgba(0, 0, 0, 0.1)',
    '--search-container': 'rgba(0, 0, 0, 0.05)',
    '--placeholder': 'rgba(0, 0, 0, 0.2)',
    '--grdient-dark':
      'linear-gradient(180deg,rgba(0, 0, 0, 1),rgba(0, 0, 0, 0.76))',
    '--grdient-blue':
      'linear-gradient(180deg, #007aff, rgba(0, 122, 255, 0.67))',
    '--gradient-drak-icon':
      'linear-gradient(180deg,rgb(43, 42, 42),rgba(0, 0, 0, 0.6))',
    '--gradient-blue-icon':
      'linear-gradient(180deg,rgba(0, 122, 255, 0.6),rgba(0, 122, 255, 0.67))',
    '--card-background': '#ffffff',
    '--box-shadow-sidebar': '0 8px 16px rgba(0, 0, 0, 0.2)',
    '--blur': 'rgba(255, 255, 255, 0.5)',
  },
};

export const macDark: Theme = {
  name: 'macDark',
  properties: {
    '--text-primary-color': '#ffffff',
    '--select_background': 'rgba(255, 255, 255, 0.1)',
    '--icon-backgound': '#000000',
    '--background-color': '#2a2a2a',
    '--breadcrumbs-disabled': 'rgba(255, 255, 255, 0.4)',
    '--breadcrumbs-line': 'rgba(255, 255, 255, 0.4)',
    '--box-shadow-select': '0px 1px 0px 0px rgba(0, 0, 0, 0.1)',
    '--search-container': 'rgba(255, 255, 255, 0.1)',
    '--placeholder': 'rgba(255, 255, 255, 0.2)',
    '--grdient-dark':
      'linear-gradient(180deg,rgba(0, 0, 0, 1),rgba(255, 255, 255, 0.1))',
    '--grdient-blue':
      'linear-gradient(180deg,rgba(10, 132, 255, 0.5),rgba(10, 132, 255, 1))',
    '--gradient-drak-icon':
      'linear-gradient(180deg,rgba(255, 255, 255, 0.2),rgba(255, 255, 255, 0.5))',
    '--gradient-blue-icon':
      'linear-gradient(180deg,rgba(0, 122, 255, 0.6),rgba(0, 122, 255, 0.67))',
    '--card-background': 'rgba(255, 255, 255, 0.05)',
    '--box-shadow-sidebar': '0 8px 16px rgba(0, 0, 0, 0.5)',
    '--blur': 'rgba(0, 0, 0, 0.5)',
  },
};
